# Generated by Django 3.0.3 on 2020-02-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('year_of_construction', models.DateField()),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ['year_of_construction'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bricks', models.PositiveIntegerField()),
                ('date_and_time', models.DateTimeField()),
                ('house', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brick_counter.House', verbose_name='Дом для закладки кирпичей')),
            ],
            options={
                'verbose_name': 'Задание на закладку кирпичей',
                'verbose_name_plural': 'Задания на закладку кирпичей',
                'ordering': ['date_and_time'],
            },
        ),
    ]
